### PR TITLE
Use default version of commontator gem instead of own fork

### LINKED ISSUE #445: Switch back to official release of Commontator gem
Currently we are using a [fork](https://github.com/MaMpf-HD/commontator) of the [commontator gem](https://github.com/lml/commontator) because of this [issue](https://github.com/lml/commontator/issues/200) in commontator, which prevents that our customized commontator/comments_controller is being used, resulting in issue #389. The change was done in #390. Since then, a workaround has been proposed in [here](https://github.com/lml/commontator/issues/200#issuecomment-1231456146). We could try if it works out for us and if yes, change back to the official release.

### PR DESCRIPTION
**Pull request by fosterfarrell9**
In this PR we switch back to the current version of the commontator gem hosted on github, no longer using our own fork. This fixes #445.

### CODE REVIEW

**Comment by fosterfarrell9** [comment]
Note that the linter fails because of several style violations in the original commontator comments controller from the gem istelf, which is only slightly modified by us. I let rubocop autocorrect several of these, but I am not sure how to proceed with the rest - do we correct them or do we leave them? There is the possibility that the original file gets an update when the gem updates (although this is rather unlikely given that the last change in this file was 4 years ago).

**Comment by Splines** [comment]
> There is the possibility that the original file gets an update when the gem updates

I'm not sure I understand what you mean here. After merging this PR, don't we have a custom controller which allows us to hook into the relevant parts of Commontator? If so, why should our custom controller be touched when the commontator gem is updated in the future and they change something internally in their library?

In the case we just copied a controller file of theirs: isn't there another way to only change what we really want to change, so that we don't depend on their implementation details of the library?

**Review by Splines — APPROVED** [review]
looks fine now and is working properly

**Comment by Splines** [comment]
remember to **squash and merge** instead of creating a merge commit ;)

**Pull request merged**
