### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by henrixapp**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **Please check if the PR fulfills these requirements**

- [ ] E2E Tests for the changes have been added  via Cypress
- [ ] Meaningful rspec tests have been added
- [ ] Docs have been added / updated 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by Splines** [comment]
@henrixapp I will definitely not review 1,375 files 🙈

This is probably for the initial setup of the docs page, right?
What about getting the minimal example of the docs page working in this PR? (by the way nice job, Docusaurus looks great 👍) Then, we would have the initial setup going and with a short Readme on how to edit and deploy this, we could always extend the docs in the future.

**Comment by henrixapp** [comment]
> @henrixapp I will definitely not review 1,375 files 🙈

Hmm, I am not sure, why you are tagging me here..., lets check who is the real owner of this branch/folder:

```
>  git shortlog -sn -- docs
   236  hungrywords
    26  Rasteter, Janina
     7  Fabian Kontor
     6  Henrik Reinstädtler
```
So I own a measly 6 out of a total of 275 commits in this folder and I am currently only contributing to mampf on a voluntary, open source and unpaid basis.  
Yes, I started this branch a year and a three quarters ago, before I left my position at Mampf.
But no, I am not in charge anymore.

I will now leave my thoughts below.
> This is probably for the initial setup of the docs page, right? 

Well, it used to be. The decision was made to fully migrate the old wiki into the repository (and executed by @hungrywords). 

Core Idea was to have three sections for teachers, students and developers in the navbar and use the docusaurus techniques to link them properly. Images (png) are stored in LFS, which allows us to minimize the core size of the git project.
 
> What about getting the minimal example of the docs page working in this PR? (by the way nice job, Docusaurus looks great 👍) Then, we would have the initial setup going and with a short Readme on how to edit and deploy this, we could always extend the docs in the future.

The minimal version is already deployed at https://mampf-hd.github.io/mampf/ and there is an auto publisher already in place as gh-action (in the overview of the files changed like the second  change that's popping up). This gh-action probably needs some modernization. I would recommend not to start new by throwing away all of @hungrywords work and have a minimal example, but it is up to you 😉 .

**Comment by Splines** [comment]
> So I own a measly 6 out of a total of 275 commits in this folder and I am currently only contributing to mampf on a voluntary, open source and unpaid basis.
Yes, I started this branch a year and a three quarters ago, before I left my position at Mampf.
But no, I am not in charge anymore.

Sorry, instead of just looking at the top seeing you as the one who opened this PR, I should have looked closer at the commits ;) And yeah of course, you're not obliged to do anything here anymore, but every contribution is appreciated and I thought that you might have wanted to keep working on the PR if (if you had really worked on most of the commits, which is however not the case as I just found out).

> I would recommend not to start new by throwing away all of @hungrywords work and have a minimal example, but it is up to you 😉 .

I thought of the docs page deployed from this PR here as the "minimal example" for the documentation. Should have rather coined it as "first docs setup" as I have just realized how much sites there are already filled in the docs, especially related to the ["instructions for editors"](https://mampf-hd.github.io/mampf/mampf-pages/all-pages-ed). So, it's not really a "minimal" example anymore. And no, I will definitely not get rid of @hungrywords work in the documentation.

## What's next
There's probably no way around reviewing all 1,375 files here and I will do this in the future, but consecutively in small chunks, e.g. only 100 files a day. So, it will take a while. But I think it's worth merging this PR in the end, so that we can continue to work on the docs in hopefully smaller PRs by then 😅

**Comment by Splines** [comment]
Thanks a lot for the efforts with the docs! We will close this PR as we are currently focusing on other things like shipping new features. But don't worry, the branch won't be deleted and the respective [docs GitHub.io page](https://mampf-hd.github.io/mampf/) will stay online. We've also included a [note in the wiki](https://github.com/MaMpf-HD/mampf/wiki).

It's just that with the limited time of people working on MaMpf, we won't be able to keep the docs up-to-date. They are still very useful, e.g. pages like the [quiz editor](https://mampf-hd.github.io/mampf/mampf-pages/quiz-editor/) can be sent to people who have difficulties setting up new quizzes. It might also serve as a good link to be sent to adjudicators, should we promote MaMpf in some funding program. And the closed PR can still be opened again in the future.

**Pull request closed without merging**
